application: cop4990-psanders-final
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: img

- url: /css
  static_dir: templates/css

- url: .*
  script: muse.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
